version: 2.1

commands:
  setup-executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

  checkout-all:
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive

  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init deps/readies
            ./deps/readies/bin/getpy3

  prebuild:
    steps:
      - setup-executor
      - checkout-all
      - setup-automation
      - run:
          name: Setup Docker
          command: |
            docker login --username redisfab --password "$DOCKER_REDISFAB_PWD"

  vm-prebuild:
    steps:
      - checkout-all
      - setup-automation
      - run:
          name: Setup Docker
          command: |
            bash <(curl -fsSL https://get.docker.com)
            docker version
            docker login --username redisfab --password "$DOCKER_REDISFAB_PWD"

jobs:
  build-x64:
    parameters:
      platform:
        type: string
    docker:
      - image: 'debian:buster'
    steps:
      - prebuild
      - run:
          name: Build
          command: |
            docker version
            make build publish OSNICK=<<parameters.platform>> STD_VERSIONS=1
          no_output_timeout: 30m

  build-arm8:
    parameters:
      platform:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - vm-prebuild
      - run:
          name: Build
          command: |
            docker version
            make build publish OSNICK=<<parameters.platform>> STD_VERSIONS=1
          no_output_timeout: 30m


on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/


workflows:
  version: 2
  general:
    jobs:
      - build-x64:
          <<: *on-any-branch
          matrix:
            parameters:
              platform: [ol8, centos7, hirsute, focal, bionic, xenial, trusty, bullseye, buster, fedora33] # centos8, alpine3, alpineedge
          context: common
      - build-arm8:
          <<: *on-any-branch
          matrix:
            parameters:
              platform: [centos7, hirsute, focal, bionic, xenial, trusty, bullseye, buster, fedora33] # centos8, alpine3, alpineedge
          context: common

  weekly:
    triggers:
      - schedule:
          # Run on Sundat 21:17 [M H DoM M DoW]
          cron: "21 17 * * 0"
          filters:
             branches:
               only: master
    jobs:
      - build-x64:
          matrix:
            parameters:
              platform: [ol8, centos7, hirsute, focal, bionic, xenial, trusty, bullseye, buster, fedora33] # centos8, alpine3, alpineedge
          context: common
      - build-arm8:
          matrix:
            parameters:
              platform: [centos7, hirsute, focal, bionic, xenial, trusty, bullseye, buster, fedora33] # centos8, alpine3, alpineedge
          context: common
